### ISSUE TITLE
File error when running compute_binned_met_counts function

### ISSUE THREAD

**Issue by JiayiLi21** [yasin-uzun/MethylPredict.1.0#1]
Hi @yasin-uzun 

I am trying the maple model on our new mouse embryo data, I have run your example and just encountered errors when using our cov_files, it is weird. I have processed and checked our input to be the standard format as your example provided. I am wondering what causes this error:
#Compute binned data
binned_list = compute_binned_met_counts(cov_dir = cov_dir, annot_file = annot_file )
Errors:
[1] 1
[1] NA
[1] 0
character(0)
[1] "Error in compute_binned_met_counts: task 1 failed - \"File '/mnt/users/jiayi/workspace/MAPLE/example/cov_files/NA' does not exist or is non-readable. getwd()=='/mnt/users/jiayi/workspace/MAPLE/annot'\""

these two screenshots are preview of my input:
<img width="692" alt="Screenshot 2024-08-03 at 21 23 41" src="https://github.com/user-attachments/assets/43ad7ca3-2737-43a0-88d0-55e637fc5002">
<img width="952" alt="Screenshot 2024-08-03 at 21 25 18" src="https://github.com/user-attachments/assets/7a0cd7b4-de25-4ded-a31a-ac9b79e50dff">

**Comment by yasin-uzun** [comment]
Hi Jiayi,

This looks like a simple file I/O error. I am suspecting that the comma (",") character in the file names might be causing trouble for R when trying to read the files. Can you replace "," character with "_" in the file names and try again?

Another thing to check is the directory and file access permissions. Make sure the directory and files are accessible for read operation (via chmod).

**Comment by JiayiLi21** [comment]
Hi @yasin-uzun 

Thank you for your reply! I just tried renaming files and checked access permissions, but still got the same error. I was quite confused, and would be super grateful if you can help! Below are the screenshots

[R code running:]
![R code running](https://github.com/user-attachments/assets/32dc52d4-9232-41c2-90eb-2e84135d725a)


[Error:]
![error](https://github.com/user-attachments/assets/9c697cac-1e79-44b1-8cb0-05e0a11780d3)


[command for troubleshooting:]
![debug_command](https://github.com/user-attachments/assets/8eba1d32-5a2a-4abc-967b-8a07641d1ef9)


[renamed files:]
![renamed_files](https://github.com/user-attachments/assets/7978ca4d-4c81-4fb4-b79d-87791399aebb)

**Comment by yasin-uzun** [comment]
Hi Jiayi,

That's interesting. What do you get when you run the following?

print(cov_dir)
print(list.files(cov_dir))

**Comment by JiayiLi21** [comment]
Hi Yasin,

I just run the print and checked the file permission, here is the screenshot , still not sure what is the problem. 

print(cov_dir)
print(list.files(cov_dir))

<img width="705" alt="Screenshot 2024-08-06 at 16 06 13" src="https://github.com/user-attachments/assets/c418ad03-b78f-40b4-835f-8dca40c54770">

**Comment by yasin-uzun** [comment]
Hi Jiayi,

You were able to run MAPLE with the example data we have, but it fails with your own data, right? Can you share this folder or part of it via Google Drive or something similar and share with me (yasin.delco at gmail com). I can give it a try to diagnose.

**Comment by JiayiLi21** [comment]
yeah I was able to run the workflow on the given example data. I just emailed you with link to part of our data. 
Thank you so much!!

**Comment by yasin-uzun** [comment]
Hi Jiayi,

I found out the source of the problem. MAPLE assumes that there are multiple types of methylation (CpG, CpH, etc.) in the folder and the methylation type is denoted explicitly in the file name. Then it filters the files by that. Since this prefix ("CpG") does not exist in your file names it is throwing error. To overcome this problem and run the compute_binned_met_counts function, you can pass the methylation_type argument empty as follows:

`
binned_list = compute_binned_met_counts(cov_dir = cov_dir, annot_file = annot_file, methylation_type = "")
`

This should supposedly solve the problem. Sorry, this should have been explained in the README document. I will update it shortly.

**Comment by JiayiLi21** [comment]
Thank you so much for the help!! It works for part of our data this time.  Also I'm quite curious about if it is possible for the maple package to re-train the model on our new data?

**Comment by yasin-uzun** [comment]
No problem. Can you open a "new issue" for the training question, as it is a separate subject? I will close this issue.

**Comment by yasin-uzun** [comment]
I am closing this issue as the problem seems resolved. You can open a new issue for the training question.
