### ISSUE TITLE
Code option to re-train the Maple framework on new data

### ISSUE THREAD

**Issue by JiayiLi21** [yasin-uzun/MethylPredict.1.0#2]
Hi Yasin,

I am trying the Maple package on new data, and just wondering is there any code support to re-train and test the model on new dataset in general.

Thank you!

**Comment by yasin-uzun** [comment]
Hi Jiayi,

For training, you need to have a true single-cell multiomics dataset. More speficially, it is necessary to have gene expression and DNA methylation from the same cells via a joint assay protocol such as scM&T-seq or scNMT-seq. Do you have such a dataset for training?

**Comment by JiayiLi21** [comment]
Hi Yasin,

Our data does have paired measurement of DNA methylation and RNA expression from the same cell

**Comment by yasin-uzun** [comment]
Sounds good. The reason that I did not include the training component in the package was that for most single-cell multi-omics datasets available by the time, cell labeling was not clean and clear. Not all the cells were true multi-omics (some of them had RNA but not DNA and vice versa). Same cells were named with different conventions in two modalities and so on. I thought it would be a quite tedious process for any user to preprocess and clean these datasets and train the models. Hence, I had shared the pretrained models instead.

I will try to retrieve the training scripts and share them among the files.

**Comment by yasin-uzun** [comment]
Hi Jiayi,

I uploaded the training scripts to the repository. You can find them in here: 
https://github.com/yasin-uzun/MAPLE.1.0/tree/master/R/TRAINING/

But, because it has been a quite long time, I am not 100% sure they were the latest, tested, bug-free versions. You may need to fix some bugs, if there are any. I hope they help.

**Comment by yasin-uzun** [comment]
I am closing this issue, assuming that it is resolved. If not, you can open a new issue.
