### ISSUE TITLE
[compute_binned_met_counts] Error in rind(deparse. level, ...) : numbers of columns of arguments do not match

### ISSUE THREAD

**Issue by JiayiLi21** [yasin-uzun/MethylPredict.1.0#3]
Hi Yasin,

While I was able to went through the workflow on a subset of 100 cells of our data ([link to previous issue](https://github.com/yasin-uzun/MAPLE.1.0/issues/1)), a problem related to rbind came up when I run compute_binned_met_counts on all ~14k cells of our data. I was checking the source code and confused about why we got this error when running all the data. 

p1: previous returned binned list on subset of our data
![Binned_list_subset100](https://github.com/user-attachments/assets/027e6526-80f7-4a8f-89ef-2e32c3ab0433)

p2: running process on data for all 14453 cells
<img width="696" alt="processing" src="https://github.com/user-attachments/assets/e25033df-a64f-40aa-a883-7be52e0fec00">

p3: Error in rind(deparse. level, ...) : numbers of columns of arguments do not match
<img width="701" alt="rbind_error_allData" src="https://github.com/user-attachments/assets/e70ac466-092e-47f2-b17f-59075b004aa4">

**Comment by yasin-uzun** [comment]
Hi Jiayi,

I think this happens due to extreme sparsity in some of the cells. MAPLE fails to work for the cells for which the data is very sparse (very few aligned reads). Filtering out the cells that has less than certain number of aligned reads may possibly solve the problem. This is a common practice in single-cell methylation data processing. You can set the threshold (minimum number of aligned reads) to 500K, 1M, 2M and see how many cells are filtered out/left and try running again.

Also, is your protocol genome-wide (such as scwgbs) or enriched for several genes only? MAPLE works for the data generated via genome-wide protocols.

**Comment by JiayiLi21** [comment]
Hi Yasin,

Thank you! Our protocol is genome wide. I just checked the distribution of the aligned reads across cells, and set the threshold to 10k reads (around 6k cells used), will try more threshold settings. Just wondering did you set some hard threshold in your code?
![n_obs](https://github.com/user-attachments/assets/e3d73b6a-0578-41cc-a5e1-3d8b1c7e1d75)

**Comment by yasin-uzun** [comment]
Hi Jiayi,

I didn't place any threshold in MAPLE for cell filtering. I assumed that cells (i.e cov files) are already cleaned and filtered prior to running MAPLE.

I don't know the specifics of your experiment, but 10k limit might be somewhat low for filtering out low quality cells. In the snmC-Seq paper (PMID: 28798132), the authors used 400K non-clonal mapped reads as threshold. 

_"Data were cleaned by excluding low-quality cells using the following set of conservative
criteria, ultimately yielding 3376 cells in mouse and 2784 cells in human for analysis. First,
non-conversion rate was required to be low (≤1% in mouse and ≤2% in human). We set a
minimum on the number of non-clonal mapped reads to eliminate contaminated samples (400K
in mouse; 500K in human)."_

By "_samples_", I assume they mean "_cells_". If that's possible, you may consider sequencing deeper.

**Comment by yasin-uzun** [comment]
I hope this problem has been resolved and closing it. You can open a new issue if you are still having problems.
